### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by miaogr86** [leonardBang/flink-sql-etl#3]
hi Leonard:
问题1：
我把flink-connector-jdbc_2.11-1.11.1.jar、flink-connector-kafka_2.11-1.11.1.jar、mysql-connector-java-8.0.20.jar放到lib目录了，但是启动sql client报Caused by: java.lang.ClassNotFoundException: org.apache.flink.streaming.connectors.kafka.KafkaTableSourceSinkFactoryBase，是不是需要把依赖的jar也拷贝到lib，如：flink-connector-kafka-base_2.11-1.11.1.jar、kakfa-clients_2.4.1.jar等等
![image](https://user-images.githubusercontent.com/5835603/89143800-56f95d80-d57e-11ea-8a8f-d3f5c77df8c5.png)
![image](https://user-images.githubusercontent.com/5835603/89143916-cff8b500-d57e-11ea-8213-684a93d08274.png)

问题2：
批计算，我是通过rest api定时提交批作业的。https://ci.apache.org/projects/flink/flink-docs-release-1.11/zh/monitoring/rest_api.html
![image](https://user-images.githubusercontent.com/5835603/89144158-7a70d800-d57f-11ea-80f4-8406e2e3c9ee.png)
但是如果我没有把flink-connector-jdbc_2.11-1.11.1.jar和mysql-connector-java-8.0.20.jar拷贝到lib目录的话，批作业任务提交多了就会导致Metaspace OOM，Metaspace调多大都没用
![image](https://user-images.githubusercontent.com/5835603/89144282-d4719d80-d57f-11ea-937f-b88ab4471315.png)

非常感谢

**Comment by leonardBang** [comment]
第一个，需要使用 flink-sql-connector-kafka_2.11-1.11.1.jar, 而不是flink-connector-kafka_2.11-1.11.1.jar
第二个，你启动的集群是什么模式？Metaspace oom  通常是是codegen的 class太大和jar包太多导致。

**Comment by miaogr86** [comment]
standalone集群模式，批计算我们大量使用了org.apache.flink.connector.jdbc.JdbcInputFormat（1.10是另外一个包名）这些api，就使用了如下依赖：
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-kafka_${scala.binary.version}</artifactId>
            <version>${flink.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-jdbc_${scala.binary.version}</artifactId>
            <version>${flink.version}</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.20</version>
        </dependency>

**Comment by miaogr86** [comment]
我把flink-connector-jdbc_2.11-1.11.1.jar和mysql-connector-java-8.0.20.jar拷贝到lib就好了，kafka就没有问题，不然测试提交几十个任务就报 Metaspace OOM了

**Comment by leonardBang** [comment]
jar的加载都是一样的方式，可以稳定复现 metaspace OOM问题吗？可以的话去JIRA上建个issue来跟进

**Comment by miaogr86** [comment]
好的 我写个demo复现下 谢谢大神！！！
